// Code generated by ent, DO NOT EDIT.

package blog

import (
	"time"
)

const (
	// Label holds the string label denoting the blog type in the database.
	Label = "blog"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldSubTitle holds the string denoting the sub_title field in the database.
	FieldSubTitle = "sub_title"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldUpdateDatetime holds the string denoting the update_datetime field in the database.
	FieldUpdateDatetime = "update_datetime"
	// FieldCreateDatetime holds the string denoting the create_datetime field in the database.
	FieldCreateDatetime = "create_datetime"
	// EdgeComments holds the string denoting the comments edge name in mutations.
	EdgeComments = "comments"
	// Table holds the table name of the blog in the database.
	Table = "blogs"
	// CommentsTable is the table that holds the comments relation/edge.
	CommentsTable = "comments"
	// CommentsInverseTable is the table name for the Comment entity.
	// It exists in this package in order to avoid circular dependency with the "comment" package.
	CommentsInverseTable = "comments"
	// CommentsColumn is the table column denoting the comments relation/edge.
	CommentsColumn = "blog_comments"
)

// Columns holds all SQL columns for blog fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldSubTitle,
	FieldTags,
	FieldContent,
	FieldUpdateDatetime,
	FieldCreateDatetime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSubTitle holds the default value on creation for the "sub_title" field.
	DefaultSubTitle string
	// DefaultTags holds the default value on creation for the "tags" field.
	DefaultTags string
	// DefaultUpdateDatetime holds the default value on creation for the "update_datetime" field.
	DefaultUpdateDatetime func() time.Time
	// UpdateDefaultUpdateDatetime holds the default value on update for the "update_datetime" field.
	UpdateDefaultUpdateDatetime func() time.Time
	// DefaultCreateDatetime holds the default value on creation for the "create_datetime" field.
	DefaultCreateDatetime func() time.Time
)
