// Code generated by ent, DO NOT EDIT.

package bloglog

import (
	"time"
)

const (
	// Label holds the string label denoting the bloglog type in the database.
	Label = "blog_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBlogID holds the string denoting the blog_id field in the database.
	FieldBlogID = "blog_id"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldDetail holds the string denoting the detail field in the database.
	FieldDetail = "detail"
	// FieldClientIP holds the string denoting the client_ip field in the database.
	FieldClientIP = "client_ip"
	// FieldCreateDatetime holds the string denoting the create_datetime field in the database.
	FieldCreateDatetime = "create_datetime"
	// Table holds the table name of the bloglog in the database.
	Table = "blog_logs"
)

// Columns holds all SQL columns for bloglog fields.
var Columns = []string{
	FieldID,
	FieldBlogID,
	FieldURL,
	FieldReason,
	FieldDetail,
	FieldClientIP,
	FieldCreateDatetime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateDatetime holds the default value on creation for the "create_datetime" field.
	DefaultCreateDatetime func() time.Time
)
