// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BlogsColumns holds the columns for the "blogs" table.
	BlogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString, Unique: true},
		{Name: "sub_title", Type: field.TypeString, Default: ""},
		{Name: "tags", Type: field.TypeString, Default: ""},
		{Name: "content", Type: field.TypeString},
		{Name: "update_datetime", Type: field.TypeTime},
		{Name: "create_datetime", Type: field.TypeTime},
	}
	// BlogsTable holds the schema information for the "blogs" table.
	BlogsTable = &schema.Table{
		Name:       "blogs",
		Columns:    BlogsColumns,
		PrimaryKey: []*schema.Column{BlogsColumns[0]},
	}
	// BlogLogsColumns holds the columns for the "blog_logs" table.
	BlogLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "blog_id", Type: field.TypeInt64},
		{Name: "url", Type: field.TypeString},
		{Name: "reason", Type: field.TypeString},
		{Name: "detail", Type: field.TypeString},
		{Name: "client_ip", Type: field.TypeString},
		{Name: "create_datetime", Type: field.TypeTime},
	}
	// BlogLogsTable holds the schema information for the "blog_logs" table.
	BlogLogsTable = &schema.Table{
		Name:       "blog_logs",
		Columns:    BlogLogsColumns,
		PrimaryKey: []*schema.Column{BlogLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "bloglog_blog_id",
				Unique:  false,
				Columns: []*schema.Column{BlogLogsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BlogsTable,
		BlogLogsTable,
	}
)

func init() {
}
