// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BlogsColumns holds the columns for the "blogs" table.
	BlogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString, Unique: true},
		{Name: "sub_title", Type: field.TypeString, Default: ""},
		{Name: "tags", Type: field.TypeString, Default: ""},
		{Name: "content", Type: field.TypeString},
		{Name: "update_datetime", Type: field.TypeTime},
		{Name: "create_datetime", Type: field.TypeTime},
	}
	// BlogsTable holds the schema information for the "blogs" table.
	BlogsTable = &schema.Table{
		Name:       "blogs",
		Columns:    BlogsColumns,
		PrimaryKey: []*schema.Column{BlogsColumns[0]},
	}
	// BlogLogsColumns holds the columns for the "blog_logs" table.
	BlogLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "blog_id", Type: field.TypeInt64},
		{Name: "url", Type: field.TypeString},
		{Name: "reason", Type: field.TypeString},
		{Name: "detail", Type: field.TypeString},
		{Name: "client_ip", Type: field.TypeString},
		{Name: "create_datetime", Type: field.TypeTime},
	}
	// BlogLogsTable holds the schema information for the "blog_logs" table.
	BlogLogsTable = &schema.Table{
		Name:       "blog_logs",
		Columns:    BlogLogsColumns,
		PrimaryKey: []*schema.Column{BlogLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "bloglog_blog_id",
				Unique:  false,
				Columns: []*schema.Column{BlogLogsColumns[1]},
			},
		},
	}
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "content", Type: field.TypeString},
		{Name: "comment_id", Type: field.TypeInt64, Default: 0},
		{Name: "update_datetime", Type: field.TypeTime},
		{Name: "create_datetime", Type: field.TypeTime},
		{Name: "blog_comments", Type: field.TypeInt64, Nullable: true},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "comments_blogs_comments",
				Columns:    []*schema.Column{CommentsColumns[7]},
				RefColumns: []*schema.Column{BlogsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BlogsTable,
		BlogLogsTable,
		CommentsTable,
	}
)

func init() {
	CommentsTable.ForeignKeys[0].RefTable = BlogsTable
}
