// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jungmu/go-web/ent/bloglog"
	"github.com/jungmu/go-web/ent/predicate"
)

// BlogLogQuery is the builder for querying BlogLog entities.
type BlogLogQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.BlogLog
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BlogLogQuery builder.
func (blq *BlogLogQuery) Where(ps ...predicate.BlogLog) *BlogLogQuery {
	blq.predicates = append(blq.predicates, ps...)
	return blq
}

// Limit adds a limit step to the query.
func (blq *BlogLogQuery) Limit(limit int) *BlogLogQuery {
	blq.limit = &limit
	return blq
}

// Offset adds an offset step to the query.
func (blq *BlogLogQuery) Offset(offset int) *BlogLogQuery {
	blq.offset = &offset
	return blq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (blq *BlogLogQuery) Unique(unique bool) *BlogLogQuery {
	blq.unique = &unique
	return blq
}

// Order adds an order step to the query.
func (blq *BlogLogQuery) Order(o ...OrderFunc) *BlogLogQuery {
	blq.order = append(blq.order, o...)
	return blq
}

// First returns the first BlogLog entity from the query.
// Returns a *NotFoundError when no BlogLog was found.
func (blq *BlogLogQuery) First(ctx context.Context) (*BlogLog, error) {
	nodes, err := blq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{bloglog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (blq *BlogLogQuery) FirstX(ctx context.Context) *BlogLog {
	node, err := blq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BlogLog ID from the query.
// Returns a *NotFoundError when no BlogLog ID was found.
func (blq *BlogLogQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = blq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{bloglog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (blq *BlogLogQuery) FirstIDX(ctx context.Context) int64 {
	id, err := blq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BlogLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BlogLog entity is found.
// Returns a *NotFoundError when no BlogLog entities are found.
func (blq *BlogLogQuery) Only(ctx context.Context) (*BlogLog, error) {
	nodes, err := blq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{bloglog.Label}
	default:
		return nil, &NotSingularError{bloglog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (blq *BlogLogQuery) OnlyX(ctx context.Context) *BlogLog {
	node, err := blq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BlogLog ID in the query.
// Returns a *NotSingularError when more than one BlogLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (blq *BlogLogQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = blq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{bloglog.Label}
	default:
		err = &NotSingularError{bloglog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (blq *BlogLogQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := blq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BlogLogs.
func (blq *BlogLogQuery) All(ctx context.Context) ([]*BlogLog, error) {
	if err := blq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return blq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (blq *BlogLogQuery) AllX(ctx context.Context) []*BlogLog {
	nodes, err := blq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BlogLog IDs.
func (blq *BlogLogQuery) IDs(ctx context.Context) ([]int64, error) {
	var ids []int64
	if err := blq.Select(bloglog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (blq *BlogLogQuery) IDsX(ctx context.Context) []int64 {
	ids, err := blq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (blq *BlogLogQuery) Count(ctx context.Context) (int, error) {
	if err := blq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return blq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (blq *BlogLogQuery) CountX(ctx context.Context) int {
	count, err := blq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (blq *BlogLogQuery) Exist(ctx context.Context) (bool, error) {
	if err := blq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return blq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (blq *BlogLogQuery) ExistX(ctx context.Context) bool {
	exist, err := blq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BlogLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (blq *BlogLogQuery) Clone() *BlogLogQuery {
	if blq == nil {
		return nil
	}
	return &BlogLogQuery{
		config:     blq.config,
		limit:      blq.limit,
		offset:     blq.offset,
		order:      append([]OrderFunc{}, blq.order...),
		predicates: append([]predicate.BlogLog{}, blq.predicates...),
		// clone intermediate query.
		sql:    blq.sql.Clone(),
		path:   blq.path,
		unique: blq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BlogID int64 `json:"blog_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BlogLog.Query().
//		GroupBy(bloglog.FieldBlogID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (blq *BlogLogQuery) GroupBy(field string, fields ...string) *BlogLogGroupBy {
	grbuild := &BlogLogGroupBy{config: blq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := blq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return blq.sqlQuery(ctx), nil
	}
	grbuild.label = bloglog.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BlogID int64 `json:"blog_id,omitempty"`
//	}
//
//	client.BlogLog.Query().
//		Select(bloglog.FieldBlogID).
//		Scan(ctx, &v)
func (blq *BlogLogQuery) Select(fields ...string) *BlogLogSelect {
	blq.fields = append(blq.fields, fields...)
	selbuild := &BlogLogSelect{BlogLogQuery: blq}
	selbuild.label = bloglog.Label
	selbuild.flds, selbuild.scan = &blq.fields, selbuild.Scan
	return selbuild
}

func (blq *BlogLogQuery) prepareQuery(ctx context.Context) error {
	for _, f := range blq.fields {
		if !bloglog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if blq.path != nil {
		prev, err := blq.path(ctx)
		if err != nil {
			return err
		}
		blq.sql = prev
	}
	return nil
}

func (blq *BlogLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BlogLog, error) {
	var (
		nodes = []*BlogLog{}
		_spec = blq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*BlogLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &BlogLog{config: blq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(blq.modifiers) > 0 {
		_spec.Modifiers = blq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, blq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (blq *BlogLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := blq.querySpec()
	if len(blq.modifiers) > 0 {
		_spec.Modifiers = blq.modifiers
	}
	_spec.Node.Columns = blq.fields
	if len(blq.fields) > 0 {
		_spec.Unique = blq.unique != nil && *blq.unique
	}
	return sqlgraph.CountNodes(ctx, blq.driver, _spec)
}

func (blq *BlogLogQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := blq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (blq *BlogLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   bloglog.Table,
			Columns: bloglog.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: bloglog.FieldID,
			},
		},
		From:   blq.sql,
		Unique: true,
	}
	if unique := blq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := blq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bloglog.FieldID)
		for i := range fields {
			if fields[i] != bloglog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := blq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := blq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := blq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := blq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (blq *BlogLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(blq.driver.Dialect())
	t1 := builder.Table(bloglog.Table)
	columns := blq.fields
	if len(columns) == 0 {
		columns = bloglog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if blq.sql != nil {
		selector = blq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if blq.unique != nil && *blq.unique {
		selector.Distinct()
	}
	for _, m := range blq.modifiers {
		m(selector)
	}
	for _, p := range blq.predicates {
		p(selector)
	}
	for _, p := range blq.order {
		p(selector)
	}
	if offset := blq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := blq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (blq *BlogLogQuery) ForUpdate(opts ...sql.LockOption) *BlogLogQuery {
	if blq.driver.Dialect() == dialect.Postgres {
		blq.Unique(false)
	}
	blq.modifiers = append(blq.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return blq
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (blq *BlogLogQuery) ForShare(opts ...sql.LockOption) *BlogLogQuery {
	if blq.driver.Dialect() == dialect.Postgres {
		blq.Unique(false)
	}
	blq.modifiers = append(blq.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return blq
}

// BlogLogGroupBy is the group-by builder for BlogLog entities.
type BlogLogGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (blgb *BlogLogGroupBy) Aggregate(fns ...AggregateFunc) *BlogLogGroupBy {
	blgb.fns = append(blgb.fns, fns...)
	return blgb
}

// Scan applies the group-by query and scans the result into the given value.
func (blgb *BlogLogGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := blgb.path(ctx)
	if err != nil {
		return err
	}
	blgb.sql = query
	return blgb.sqlScan(ctx, v)
}

func (blgb *BlogLogGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range blgb.fields {
		if !bloglog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := blgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := blgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (blgb *BlogLogGroupBy) sqlQuery() *sql.Selector {
	selector := blgb.sql.Select()
	aggregation := make([]string, 0, len(blgb.fns))
	for _, fn := range blgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(blgb.fields)+len(blgb.fns))
		for _, f := range blgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(blgb.fields...)...)
}

// BlogLogSelect is the builder for selecting fields of BlogLog entities.
type BlogLogSelect struct {
	*BlogLogQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (bls *BlogLogSelect) Scan(ctx context.Context, v interface{}) error {
	if err := bls.prepareQuery(ctx); err != nil {
		return err
	}
	bls.sql = bls.BlogLogQuery.sqlQuery(ctx)
	return bls.sqlScan(ctx, v)
}

func (bls *BlogLogSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := bls.sql.Query()
	if err := bls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
