// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jungmu/go-web/ent/blog"
	"github.com/jungmu/go-web/ent/comment"
)

// CommentCreate is the builder for creating a Comment entity.
type CommentCreate struct {
	config
	mutation *CommentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (cc *CommentCreate) SetName(s string) *CommentCreate {
	cc.mutation.SetName(s)
	return cc
}

// SetPassword sets the "password" field.
func (cc *CommentCreate) SetPassword(s string) *CommentCreate {
	cc.mutation.SetPassword(s)
	return cc
}

// SetContent sets the "content" field.
func (cc *CommentCreate) SetContent(s string) *CommentCreate {
	cc.mutation.SetContent(s)
	return cc
}

// SetCommentID sets the "comment_id" field.
func (cc *CommentCreate) SetCommentID(i int64) *CommentCreate {
	cc.mutation.SetCommentID(i)
	return cc
}

// SetNillableCommentID sets the "comment_id" field if the given value is not nil.
func (cc *CommentCreate) SetNillableCommentID(i *int64) *CommentCreate {
	if i != nil {
		cc.SetCommentID(*i)
	}
	return cc
}

// SetUpdateDatetime sets the "update_datetime" field.
func (cc *CommentCreate) SetUpdateDatetime(t time.Time) *CommentCreate {
	cc.mutation.SetUpdateDatetime(t)
	return cc
}

// SetNillableUpdateDatetime sets the "update_datetime" field if the given value is not nil.
func (cc *CommentCreate) SetNillableUpdateDatetime(t *time.Time) *CommentCreate {
	if t != nil {
		cc.SetUpdateDatetime(*t)
	}
	return cc
}

// SetCreateDatetime sets the "create_datetime" field.
func (cc *CommentCreate) SetCreateDatetime(t time.Time) *CommentCreate {
	cc.mutation.SetCreateDatetime(t)
	return cc
}

// SetNillableCreateDatetime sets the "create_datetime" field if the given value is not nil.
func (cc *CommentCreate) SetNillableCreateDatetime(t *time.Time) *CommentCreate {
	if t != nil {
		cc.SetCreateDatetime(*t)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *CommentCreate) SetID(i int64) *CommentCreate {
	cc.mutation.SetID(i)
	return cc
}

// SetOwnerID sets the "owner" edge to the Blog entity by ID.
func (cc *CommentCreate) SetOwnerID(id int64) *CommentCreate {
	cc.mutation.SetOwnerID(id)
	return cc
}

// SetNillableOwnerID sets the "owner" edge to the Blog entity by ID if the given value is not nil.
func (cc *CommentCreate) SetNillableOwnerID(id *int64) *CommentCreate {
	if id != nil {
		cc = cc.SetOwnerID(*id)
	}
	return cc
}

// SetOwner sets the "owner" edge to the Blog entity.
func (cc *CommentCreate) SetOwner(b *Blog) *CommentCreate {
	return cc.SetOwnerID(b.ID)
}

// Mutation returns the CommentMutation object of the builder.
func (cc *CommentCreate) Mutation() *CommentMutation {
	return cc.mutation
}

// Save creates the Comment in the database.
func (cc *CommentCreate) Save(ctx context.Context) (*Comment, error) {
	var (
		err  error
		node *Comment
	)
	cc.defaults()
	if len(cc.hooks) == 0 {
		if err = cc.check(); err != nil {
			return nil, err
		}
		node, err = cc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CommentMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cc.check(); err != nil {
				return nil, err
			}
			cc.mutation = mutation
			if node, err = cc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(cc.hooks) - 1; i >= 0; i-- {
			if cc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, cc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Comment)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from CommentMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CommentCreate) SaveX(ctx context.Context) *Comment {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CommentCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CommentCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *CommentCreate) defaults() {
	if _, ok := cc.mutation.CommentID(); !ok {
		v := comment.DefaultCommentID
		cc.mutation.SetCommentID(v)
	}
	if _, ok := cc.mutation.UpdateDatetime(); !ok {
		v := comment.DefaultUpdateDatetime()
		cc.mutation.SetUpdateDatetime(v)
	}
	if _, ok := cc.mutation.CreateDatetime(); !ok {
		v := comment.DefaultCreateDatetime()
		cc.mutation.SetCreateDatetime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CommentCreate) check() error {
	if _, ok := cc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Comment.name"`)}
	}
	if _, ok := cc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "Comment.password"`)}
	}
	if _, ok := cc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Comment.content"`)}
	}
	if _, ok := cc.mutation.CommentID(); !ok {
		return &ValidationError{Name: "comment_id", err: errors.New(`ent: missing required field "Comment.comment_id"`)}
	}
	if _, ok := cc.mutation.UpdateDatetime(); !ok {
		return &ValidationError{Name: "update_datetime", err: errors.New(`ent: missing required field "Comment.update_datetime"`)}
	}
	if _, ok := cc.mutation.CreateDatetime(); !ok {
		return &ValidationError{Name: "create_datetime", err: errors.New(`ent: missing required field "Comment.create_datetime"`)}
	}
	return nil
}

func (cc *CommentCreate) sqlSave(ctx context.Context) (*Comment, error) {
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	return _node, nil
}

func (cc *CommentCreate) createSpec() (*Comment, *sqlgraph.CreateSpec) {
	var (
		_node = &Comment{config: cc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: comment.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: comment.FieldID,
			},
		}
	)
	_spec.OnConflict = cc.conflict
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: comment.FieldName,
		})
		_node.Name = value
	}
	if value, ok := cc.mutation.Password(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: comment.FieldPassword,
		})
		_node.Password = value
	}
	if value, ok := cc.mutation.Content(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: comment.FieldContent,
		})
		_node.Content = value
	}
	if value, ok := cc.mutation.CommentID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: comment.FieldCommentID,
		})
		_node.CommentID = value
	}
	if value, ok := cc.mutation.UpdateDatetime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: comment.FieldUpdateDatetime,
		})
		_node.UpdateDatetime = value
	}
	if value, ok := cc.mutation.CreateDatetime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: comment.FieldCreateDatetime,
		})
		_node.CreateDatetime = value
	}
	if nodes := cc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   comment.OwnerTable,
			Columns: []string{comment.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt64,
					Column: blog.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.blog_comments = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Comment.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CommentUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (cc *CommentCreate) OnConflict(opts ...sql.ConflictOption) *CommentUpsertOne {
	cc.conflict = opts
	return &CommentUpsertOne{
		create: cc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Comment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (cc *CommentCreate) OnConflictColumns(columns ...string) *CommentUpsertOne {
	cc.conflict = append(cc.conflict, sql.ConflictColumns(columns...))
	return &CommentUpsertOne{
		create: cc,
	}
}

type (
	// CommentUpsertOne is the builder for "upsert"-ing
	//  one Comment node.
	CommentUpsertOne struct {
		create *CommentCreate
	}

	// CommentUpsert is the "OnConflict" setter.
	CommentUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *CommentUpsert) SetName(v string) *CommentUpsert {
	u.Set(comment.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CommentUpsert) UpdateName() *CommentUpsert {
	u.SetExcluded(comment.FieldName)
	return u
}

// SetPassword sets the "password" field.
func (u *CommentUpsert) SetPassword(v string) *CommentUpsert {
	u.Set(comment.FieldPassword, v)
	return u
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *CommentUpsert) UpdatePassword() *CommentUpsert {
	u.SetExcluded(comment.FieldPassword)
	return u
}

// SetContent sets the "content" field.
func (u *CommentUpsert) SetContent(v string) *CommentUpsert {
	u.Set(comment.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *CommentUpsert) UpdateContent() *CommentUpsert {
	u.SetExcluded(comment.FieldContent)
	return u
}

// SetCommentID sets the "comment_id" field.
func (u *CommentUpsert) SetCommentID(v int64) *CommentUpsert {
	u.Set(comment.FieldCommentID, v)
	return u
}

// UpdateCommentID sets the "comment_id" field to the value that was provided on create.
func (u *CommentUpsert) UpdateCommentID() *CommentUpsert {
	u.SetExcluded(comment.FieldCommentID)
	return u
}

// AddCommentID adds v to the "comment_id" field.
func (u *CommentUpsert) AddCommentID(v int64) *CommentUpsert {
	u.Add(comment.FieldCommentID, v)
	return u
}

// SetUpdateDatetime sets the "update_datetime" field.
func (u *CommentUpsert) SetUpdateDatetime(v time.Time) *CommentUpsert {
	u.Set(comment.FieldUpdateDatetime, v)
	return u
}

// UpdateUpdateDatetime sets the "update_datetime" field to the value that was provided on create.
func (u *CommentUpsert) UpdateUpdateDatetime() *CommentUpsert {
	u.SetExcluded(comment.FieldUpdateDatetime)
	return u
}

// SetCreateDatetime sets the "create_datetime" field.
func (u *CommentUpsert) SetCreateDatetime(v time.Time) *CommentUpsert {
	u.Set(comment.FieldCreateDatetime, v)
	return u
}

// UpdateCreateDatetime sets the "create_datetime" field to the value that was provided on create.
func (u *CommentUpsert) UpdateCreateDatetime() *CommentUpsert {
	u.SetExcluded(comment.FieldCreateDatetime)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Comment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(comment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CommentUpsertOne) UpdateNewValues() *CommentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(comment.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Comment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CommentUpsertOne) Ignore() *CommentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CommentUpsertOne) DoNothing() *CommentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CommentCreate.OnConflict
// documentation for more info.
func (u *CommentUpsertOne) Update(set func(*CommentUpsert)) *CommentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CommentUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *CommentUpsertOne) SetName(v string) *CommentUpsertOne {
	return u.Update(func(s *CommentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CommentUpsertOne) UpdateName() *CommentUpsertOne {
	return u.Update(func(s *CommentUpsert) {
		s.UpdateName()
	})
}

// SetPassword sets the "password" field.
func (u *CommentUpsertOne) SetPassword(v string) *CommentUpsertOne {
	return u.Update(func(s *CommentUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *CommentUpsertOne) UpdatePassword() *CommentUpsertOne {
	return u.Update(func(s *CommentUpsert) {
		s.UpdatePassword()
	})
}

// SetContent sets the "content" field.
func (u *CommentUpsertOne) SetContent(v string) *CommentUpsertOne {
	return u.Update(func(s *CommentUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *CommentUpsertOne) UpdateContent() *CommentUpsertOne {
	return u.Update(func(s *CommentUpsert) {
		s.UpdateContent()
	})
}

// SetCommentID sets the "comment_id" field.
func (u *CommentUpsertOne) SetCommentID(v int64) *CommentUpsertOne {
	return u.Update(func(s *CommentUpsert) {
		s.SetCommentID(v)
	})
}

// AddCommentID adds v to the "comment_id" field.
func (u *CommentUpsertOne) AddCommentID(v int64) *CommentUpsertOne {
	return u.Update(func(s *CommentUpsert) {
		s.AddCommentID(v)
	})
}

// UpdateCommentID sets the "comment_id" field to the value that was provided on create.
func (u *CommentUpsertOne) UpdateCommentID() *CommentUpsertOne {
	return u.Update(func(s *CommentUpsert) {
		s.UpdateCommentID()
	})
}

// SetUpdateDatetime sets the "update_datetime" field.
func (u *CommentUpsertOne) SetUpdateDatetime(v time.Time) *CommentUpsertOne {
	return u.Update(func(s *CommentUpsert) {
		s.SetUpdateDatetime(v)
	})
}

// UpdateUpdateDatetime sets the "update_datetime" field to the value that was provided on create.
func (u *CommentUpsertOne) UpdateUpdateDatetime() *CommentUpsertOne {
	return u.Update(func(s *CommentUpsert) {
		s.UpdateUpdateDatetime()
	})
}

// SetCreateDatetime sets the "create_datetime" field.
func (u *CommentUpsertOne) SetCreateDatetime(v time.Time) *CommentUpsertOne {
	return u.Update(func(s *CommentUpsert) {
		s.SetCreateDatetime(v)
	})
}

// UpdateCreateDatetime sets the "create_datetime" field to the value that was provided on create.
func (u *CommentUpsertOne) UpdateCreateDatetime() *CommentUpsertOne {
	return u.Update(func(s *CommentUpsert) {
		s.UpdateCreateDatetime()
	})
}

// Exec executes the query.
func (u *CommentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CommentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CommentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CommentUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CommentUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CommentCreateBulk is the builder for creating many Comment entities in bulk.
type CommentCreateBulk struct {
	config
	builders []*CommentCreate
	conflict []sql.ConflictOption
}

// Save creates the Comment entities in the database.
func (ccb *CommentCreateBulk) Save(ctx context.Context) ([]*Comment, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Comment, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CommentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ccb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CommentCreateBulk) SaveX(ctx context.Context) []*Comment {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CommentCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CommentCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Comment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CommentUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (ccb *CommentCreateBulk) OnConflict(opts ...sql.ConflictOption) *CommentUpsertBulk {
	ccb.conflict = opts
	return &CommentUpsertBulk{
		create: ccb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Comment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ccb *CommentCreateBulk) OnConflictColumns(columns ...string) *CommentUpsertBulk {
	ccb.conflict = append(ccb.conflict, sql.ConflictColumns(columns...))
	return &CommentUpsertBulk{
		create: ccb,
	}
}

// CommentUpsertBulk is the builder for "upsert"-ing
// a bulk of Comment nodes.
type CommentUpsertBulk struct {
	create *CommentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Comment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(comment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CommentUpsertBulk) UpdateNewValues() *CommentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(comment.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Comment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CommentUpsertBulk) Ignore() *CommentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CommentUpsertBulk) DoNothing() *CommentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CommentCreateBulk.OnConflict
// documentation for more info.
func (u *CommentUpsertBulk) Update(set func(*CommentUpsert)) *CommentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CommentUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *CommentUpsertBulk) SetName(v string) *CommentUpsertBulk {
	return u.Update(func(s *CommentUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CommentUpsertBulk) UpdateName() *CommentUpsertBulk {
	return u.Update(func(s *CommentUpsert) {
		s.UpdateName()
	})
}

// SetPassword sets the "password" field.
func (u *CommentUpsertBulk) SetPassword(v string) *CommentUpsertBulk {
	return u.Update(func(s *CommentUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *CommentUpsertBulk) UpdatePassword() *CommentUpsertBulk {
	return u.Update(func(s *CommentUpsert) {
		s.UpdatePassword()
	})
}

// SetContent sets the "content" field.
func (u *CommentUpsertBulk) SetContent(v string) *CommentUpsertBulk {
	return u.Update(func(s *CommentUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *CommentUpsertBulk) UpdateContent() *CommentUpsertBulk {
	return u.Update(func(s *CommentUpsert) {
		s.UpdateContent()
	})
}

// SetCommentID sets the "comment_id" field.
func (u *CommentUpsertBulk) SetCommentID(v int64) *CommentUpsertBulk {
	return u.Update(func(s *CommentUpsert) {
		s.SetCommentID(v)
	})
}

// AddCommentID adds v to the "comment_id" field.
func (u *CommentUpsertBulk) AddCommentID(v int64) *CommentUpsertBulk {
	return u.Update(func(s *CommentUpsert) {
		s.AddCommentID(v)
	})
}

// UpdateCommentID sets the "comment_id" field to the value that was provided on create.
func (u *CommentUpsertBulk) UpdateCommentID() *CommentUpsertBulk {
	return u.Update(func(s *CommentUpsert) {
		s.UpdateCommentID()
	})
}

// SetUpdateDatetime sets the "update_datetime" field.
func (u *CommentUpsertBulk) SetUpdateDatetime(v time.Time) *CommentUpsertBulk {
	return u.Update(func(s *CommentUpsert) {
		s.SetUpdateDatetime(v)
	})
}

// UpdateUpdateDatetime sets the "update_datetime" field to the value that was provided on create.
func (u *CommentUpsertBulk) UpdateUpdateDatetime() *CommentUpsertBulk {
	return u.Update(func(s *CommentUpsert) {
		s.UpdateUpdateDatetime()
	})
}

// SetCreateDatetime sets the "create_datetime" field.
func (u *CommentUpsertBulk) SetCreateDatetime(v time.Time) *CommentUpsertBulk {
	return u.Update(func(s *CommentUpsert) {
		s.SetCreateDatetime(v)
	})
}

// UpdateCreateDatetime sets the "create_datetime" field to the value that was provided on create.
func (u *CommentUpsertBulk) UpdateCreateDatetime() *CommentUpsertBulk {
	return u.Update(func(s *CommentUpsert) {
		s.UpdateCreateDatetime()
	})
}

// Exec executes the query.
func (u *CommentUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CommentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CommentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CommentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
